apiVersion: apps/v1
kind: Deployment
metadata:
  name: swish-analytics-demo
  labels:
    app: swish-analytics-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swish-analytics-demo
  template:
    metadata:
      labels:
        app: swish-analytics-demo
    spec:
      containers:
      - name: swish-analytics-demo
        image: ellipticalgadzooks/python_r_alpine:latest
        ports:
        - containerPort: 8080
        command: ["tail"]
        args: ["-f", "/dev/null"]
